### ISSUE TITLE
Install Groups?

### ISSUE THREAD

**Issue by zQueal** [kisslinux/kiss#104]
Would be great to maintain lists which can be built/installed with a single command. `buildutils` as an example?

```bash
-> $ kiss b @build-essentials
```

Or something similar?

**Comment by dylanaraps** [comment]
A simple package can be added to your local repository which would include the list of packages as dependencies. You could even name it `@group`. 

Running `kiss b @group` will build and install the list of packages as they're detected as dependencies. You can later remove **just** the `@group` "meta" package by using `KISS_FORCE=1 kiss r @group`.

You could even automate this: `kiss b @group && KISS_FORCE=1 kiss r @group`

I don't think this is anything which needs to be added to the package manager itself.  Thanks for opening this issue. :+1:
