### ISSUE TITLE
BUG: handling soft-links with kiss-alternative

### ISSUE THREAD

**Issue by cemkeylan** [kisslinux/kiss#111]
So when you switch back and forth a package that uses soft links (busybox in this example). Instead of getting the link back to the place, you get the copy of the program.

Steps to reproduce
-----------------------------------------------------------------

```sh
# For sbase and busybox

readlink /usr/bin/sort  # outputs busybox
kiss a sbase /usr/bin/sort
kiss a busybox /usr/bin/sort
readlink /usr/bin/sort  # no output as it is now busybox renamed as sort
```

This is just a simple way of reproducing. I have replaced the whole sbase/busybox and it
added more than 60MiB to my system. This is not a small value it can lead to bigger issues.

**Comment by dylanaraps** [comment]
Fixed, thanks. :+1:
