### ISSUE TITLE
Unsure of source of `pkg` variable

### ISSUE THREAD

**Issue by Akeboshiwind** [kisslinux/kiss#114]
Hey, I'm probably just missing a feature of `sh` I didn't know about, but where is the source of this `pkg` variable you use all over the place. I can't see it being set anywhere and it should just default to empty.

Edit: I forgot to add an example: https://github.com/kisslinux/kiss/blob/9d19826b85de1864293f556e87a86500fbff8243/kiss#L167

**Comment by dylanaraps** [comment]
When omitted, `for var` will iterate over `$@`.

**Comment by Akeboshiwind** [comment]
Thanks :)
