### ISSUE TITLE
Feature request: Status bar, name of current package

### ISSUE THREAD

**Issue by sdsddsd1** [kisslinux/kiss#120]
E.g when building dependency-chains I can just guess which package KISS
is building right now. Would it be possible to nest the build process in some kind of status bar with the name of the current package?

**Comment by dylanaraps** [comment]
I think it's out of scope for the package manager to venture into what I'd call "TUI territory". This opens up a whole can of worms as there's a lot to take into account. 

What you can do is script around the package manager hooks. You are able to react to a series of events and what you're asking for (a way to know which package is currently building) can be accomplished this way.

See the man page as well as my personal hook script here: https://github.com/dylanaraps/bin/blob/master/kh
