### ISSUE TITLE
let `kiss l` keep going even if a package is not installed

### ISSUE THREAD

**Issue by zenyusy** [kisslinux/kiss#124]
when running `kiss l pkg1 pkg2 pkg3 ...`, it'll die as long as any single pkg is not installed.
this appears inconvenient if i have a few pkgs to check and wanna see which pkgs are installed and which are not.

maybe change "return 1" to "continue" ?:  https://github.com/kisslinux/kiss/blob/02106cb810f2490fb46880b987f700f416bd7383/kiss#L176

**Comment by dylanaraps** [comment]
The package manager relies on the current behavior as it uses `kiss l` internally. You can very easily script your own solution as it's simply checking `/var/db/kiss/installed`. :+1:
