### ISSUE TITLE
failure in figuring out the owner in pkg_fixdeps()

### ISSUE THREAD

**Issue by zenyusy** [kisslinux/kiss#127]
on my computer (LD_LIBRARY_PATH not set), extracted filepath from `ldd` is like **/lib/libfoo.so.x**, while the corresponding record in this lib's manifest file is like **/usr/lib/libfoo.so.x**.
so `grep -x` cannot find out the real owner of this lib.

please correct me if i misunderstand something here.

https://github.com/kisslinux/kiss/blob/55c2de2af8a069678c40f9d495847ca6a3e0b60e/kiss#L401-L410

**Comment by dylanaraps** [comment]
I need to see the package you are trying to build and the terminal output from `kiss`. The manifest file will also be handy.

**Comment by dylanaraps** [comment]
Should be fixed as of: https://github.com/kisslinux/kiss/commit/9186e2105d5092fc3ae2393dc99286c603f77d35
