### ISSUE TITLE
ubase stat doesn't have -c option

### ISSUE THREAD

**Issue by illiliti** [kisslinux/kiss#128]
https://github.com/kisslinux/kiss/blob/041d8906c728eae486bd94aa3a275c6768dfb062/kiss#L1056

**Comment by cemkeylan** [comment]
Yeah, that is an issue on my end, I am the maintainer of `ubase` on the community repository. `stat -c` is pretty much the same as the `sed -i` issue. It is extremely widely used, pretty much exist in every implementation except `ubase` (which was the case for why we dropped the `sed` link in `sbase`).

Some other longer function could be used to get username. `stat -t` is same across every implementation, which you can parse the userid from and get the username (from passwd).

`stat` is a GNU Coreutils program that is not defined by POSIX, so we are not dealing with 'keeping with the standards' either. I would call for unlinking `stat` from `ubase` (which means it can only be called by `ubase-box stat` unless linked to the system manually by the user).

**Comment by cemkeylan** [comment]
I am dumb. `ubase stat` is already unlinked in the community repository.
