### ISSUE TITLE
fixdeps fails if "depends" file does not exists

### ISSUE THREAD

**Issue by zenyusy** [kisslinux/kiss#132]
if a package has no "depends" file in repo, yet it actually depends on something. the diff-patch method in pkg_fixdeps() doesn't work.

https://github.com/kisslinux/kiss/blob/041d8906c728eae486bd94aa3a275c6768dfb062/kiss#L428

just try `echo 123 | diff - nosuchfile 2>/dev/null`, which has no output. (btw, `sort`, as part of the pipeline chain, may complain "standard output: Broken pipe" due to this)

**Comment by zenyusy** [comment]
welcome back dylan, long time no see XD

why not https://github.com/kisslinux/kiss/blob/7f22697bdc844948f4c684480b9d95239cb2aa87/kiss#L444-L445

**Comment by dylanaraps** [comment]
Thanks, added. :)
