### ISSUE TITLE
Can't remove circular dependencies

### ISSUE THREAD

**Issue by trbednarzyk** [kisslinux/kiss#142]
As the title says, if two packages rely on each other, running `kiss r <pkg1> <pkg2>` cannot remove either of them. I wanted to switch `mpd` with `cmus` because I haven't been able to get cue files into `mpd`'s database, so when I was done installing `cmus` I tried to uninstall `mpd` and its clients. However, `mpd` and `libmpdclient` depend on each other it seems, and the package manager complains no matter what I do. Below is my attempt to uninstall either program:
```
~ $ kiss r mpd libmpdclient
-> Using '/usr/bin/sudo' (to become root)
-> libmpdclient Checking for reverse dependencies
mpd/depends
!> libmpdclient Can't remove package, others depend on it
~ $ kiss r libmpdclient mpd
-> Using '/usr/bin/sudo' (to become root)
-> libmpdclient Checking for reverse dependencies
mpd/depends
!> libmpdclient Can't remove package, others depend on it
~ $ kiss r mpd
-> Using '/usr/bin/sudo' (to become root)
-> mpd Checking for reverse dependencies
libmpdclient/depends
!> mpd Can't remove package, others depend on it
~ $ kiss r libmpdclient
-> Using '/usr/bin/sudo' (to become root)
-> libmpdclient Checking for reverse dependencies
mpd/depends
!> libmpdclient Can't remove package, others depend on it
```
What I propose for a fix is that the package manager should just allow removing a package if all of its dependencies are also listed for removal.

**Comment by dylanaraps** [comment]
Circular dependencies aren't a supported feature (I wouldn't call them a feature at all) and you should be able to simple `KISS_FORCE=1 kiss r pkg pkg` to bypass the error. 

This is a bug in both of the `mpd` packages as they should be merged into a simple `mpd` package (similar to freetype-harfbuzz and the circular dependency). Something must be done to fix the packages. I'd contact the maintainer `(kiss maintainer mpd`).
