### ISSUE TITLE
Feature request: kiss-outdated for not installed pkg

### ISSUE THREAD

**Issue by sdsddsd1** [kisslinux/kiss#144]
I have modified `kiss-outdated` to check my personal repos for outdated packages.
I think this is useful for other personal repos aswell.  
A nice addition would be to set the directory from outside but I am not able to write  
this kind of script in a nice way (:  
```
#!/bin/sh
#
# Check a whole repository for updates.

old_IFS=$IFS

# List via arguments or all installed packages.
if [ "$1" ]; then
    set -- printf '%s\n' "$@"
else
    set -- ls /home/claudia/repos/kiss-games
fi

"$@" | (while read -r pkg _; do {
    read -r ver _ < "/home/claudia/repos/kiss-games/$pkg/version"

    # Fix some package names.
    case $pkg in
        *-bin) fix=${pkg%%-bin} ;;
    esac
....
....
....
```

**Comment by dylanaraps** [comment]
Fixed, thanks. Made the script check all repositories for outdated packages (controllable via `KISS_PATH` of course). Just do: `KISS_PATH=/path/to/myrepo kiss outdated`.
