### ISSUE TITLE
kiss can not remove packages with special characters

### ISSUE THREAD

**Issue by sdsddsd1** [kisslinux/kiss#148]
Kiss can not remove packages with special characters.
Maybe it shouldnt be able to process them in the first place.
Anyway it was not a good idea to pick a special character.

```
~/myrepo/oshu!$ ➜  kiss l | grep oshu
oshu! 2.0.1 1
~/myrepo/oshu!$ ➜  kiss r oshu!
ERROR Arguments contain invalid characters: '!*[]'
```

**Comment by E5ten** [comment]
Does that package still build with current kiss? Because from what I can see from looking at the code, it would seem that same error would appear when trying to build or install a package with special characters in the name.

**Comment by sdsddsd1** [comment]
`kiss b`  and `kiss c` works. But no kiss-depends, manifest and remove.

**Comment by E5ten** [comment]
Can you check what happens with kiss from git master?

**Comment by sdsddsd1** [comment]
kiss from master errors already out while trying to build.
```
/tmp/kiss$ ➜  ./kiss b ~/myrepo/oshu!/
ERROR Arguments contain invalid characters: '!*[]'
```

**Comment by E5ten** [comment]
So I guess this is fixed in master then?

**Comment by sdsddsd1** [comment]
I let it close by dylan?

**Comment by dylanaraps** [comment]
Fixed. Using `PWD` was letting through invalid characters.
