### ISSUE TITLE
kiss: fails without full path to *.tar.gz

### ISSUE THREAD

**Issue by sdsddsd1** [kisslinux/kiss#156]
Kiss still fails without specifying the full path to the tarball.
[16e40cb](https://github.com/kisslinux/kiss/commit/16e40cb0fa80714fd674de54ad8aa25f4ca27740) has no effect on my end.
```
~$ ➜  ls | grep webkit
webkit2gtk#2.28.2-2.tar.gz
~$ ➜  kiss i webkit2gtk\#2.28.2-2.tar.gz
-> Using '/usr/bin/doas' (to become root)
ERROR package has not been built, run 'kiss b pkg'
```

**Comment by dylanaraps** [comment]
It needs to be a full path and not a relative one. It's working as intended.
