### ISSUE TITLE
Manifest disappearing because of sed error in pkg_swap

### ISSUE THREAD

**Issue by FriendlyNeighborhoodShane** [kisslinux/kiss#162]
Hello! I really like what you've done here. I was skeptical about a shell package manager, but this is really elegant.

There seems to be a bug in the `pkg_swap` function that makes package manifests disappear. I've encountered it between `busybox` and community's `coreutils`.

Reproducing:
 - Install `busybox`, install `coreutils` over it
   - `kiss man` on both, manifests OK
 - `kiss a | grep ^coreutils | kiss a -`
   - `sed: unmatched ''` error
   - `ERROR File X exists on filesystem but isn't owned` from kiss
 - `kiss man` both `coreutils` and `busybox`, both empty
   - So are their manifest files in sys_db
 - Reinstall them, their manifests come back

My `sed` is from the latest `busybox` build, v1.31.1

Looking at the code, it seems that the `sed` error is in the `pkg_swap` function, line 880. On the first swap, `sed` errors out so obviously no output but `kiss` thinks it's okay and the empty file is copied to the installed manifest. And then the second swap fails because of the empty manifest, and `kiss` dies.

Besides fixing the `sed` error, maybe a return code or `||` check in that sed statement might be apt?

Thanks and good luck!

UPDATE: O shit, just did `kiss a | grep ^coreutils | head` and realised why. The first bin to be swapped is `[` and sed (and grep and literally every other processing util) automatically assumes it to be a charachter set.

**Comment by dylanaraps** [comment]
Thanks for reporting this issue. :+1:

**Comment by dylanaraps** [comment]
I've pushed out a package manager update. (Run `kiss u`). :+1:

**Comment by FriendlyNeighborhoodShane** [comment]
Wow, you're quick :P

Thanks!

**Comment by FriendlyNeighborhoodShane** [comment]
@dylanaraps the same regex-char problem exists with kiss-owns (though it dies gracefully instead of silent catastrophe)
