### ISSUE TITLE
Feature request: Add provides file

### ISSUE THREAD

**Issue by depsterr** [kisslinux/kiss#163]
Currently there is a bit of an issue with kiss, lets say there is a binary, git and release version of a package and then this package is used by another package as a dependency.

Currently you would have to choose one of these versions of the package as the dependency, which of course isn't optimal.

I understand if you do not wish to change this to keep kiss more minimal.

If not, might you consider either letting each package have an optional provide file, which lists other packages it provides. This might make looking up dependencies slower / harder, but is probably the most convenient solution to this issue.

This is also useful for compilers / lanuages. I created the ghc-bin package in community, however with a provides file one could also create a ghc package that builds from source since it could use ghc as a make dependency provided by ghc-bin. That way those who wish could use ghc-bin to build ghc and then remove ghc-bin and keep using ghc to rebuild itself once it updates.

**Comment by konimex** [comment]
I think there are two ways this can happen:

1. A `provides` file, like OP suggests
2. (ab)Using symlinks, much like #65

However, there might be trade-offs between the two solutions.

**Comment by dylanaraps** [comment]
I'm somewhat reluctant to add more files to the package system. I very much
enjoy the simplicity the format provides in its current state and I think we'll
draw the line here.

Symbolic links are workable for this use-case. Using `readline`/`editline` as an
example, one could symbolically link `readline` to `editline` (or vice versa) in
their own repository (start of KISS_PATH) and the desired alternative library
will be used.

Symbolic links can also be used at the file level for finer control over
dependencies (and everything else). If `bash` depends on `readline` for
instance, you could create your own `bash` package, symlink everything but the
`depends` file to Community (or wherever `bash` is located) and finally modify
the `depends` file to use `editline` in its place.

(KISS has tooling for this via the `kiss-*` extensions. `kiss fork` and
`kiss link` can be used to automate this.)

All in all, I don't believe we need to add any additional files to the package
system (at this stage) as there are methods of accomplishing this already.
Thanks for opening this issue. :)

**Comment by konimex** [comment]
> Symbolic links are workable for this use-case. Using readline/editline as an
example, one could symbolically link readline to editline (or vice versa) in
their own repository (start of KISS_PATH) and the desired alternative library
will be used.

Speaking of symlinks, what if:

Suppose there are 3 packages. Call it `gzip`, `dummy` and `pigz`. `pigz` provides `gzip`, and `dummy` needs `gzip`.

If, in a case, say, `/var/db/kiss/repo-a` has `gzip` (the package dir, not the program) linked to `pigz`. And a package in `/var/db/kiss/repo-b`, `dummy`'s dependency file has a few dependencies, including `gzip`. Is it possible (already) for the package manager to check if the `gzip` in `repo-a` is a symlink (and if the symlinked dir `pigz` exists and installed, returns 0, otherwise attempt to install pigz)?

**Comment by dylanaraps** [comment]
That should be very doable. Great idea.

**Comment by dylanaraps** [comment]
> > Symbolic links are workable for this use-case. Using readline/editline as an
> > example, one could symbolically link readline to editline (or vice versa) in
> > their own repository (start of KISS_PATH) and the desired alternative library
> > will be used.
> 
> Speaking of symlinks, what if:
> 
> Suppose there are 3 packages. Call it `gzip`, `dummy` and `pigz`. `pigz` provides `gzip`, and `dummy` needs `gzip`.
> 
> If, in a case, say, `/var/db/kiss/repo-a` has `gzip` (the package dir, not the program) linked to `pigz`. And a package in `/var/db/kiss/repo-b`, `dummy`'s dependency file has a few dependencies, including `gzip`. Is it possible (already) for the package manager to check if the `gzip` in `repo-a` is a symlink (and if the symlinked dir `pigz` exists and installed, returns 0, otherwise attempt to install pigz)?

This is the likely approach that will be taken. Thanks for reminding me (and again for coming up with it). Work I've done to the package manager this month should soon make this possible (some more foundational code changes are needed yet). Dunno if this will be done anytime *soon*. Just left a note for myself in the kisslinux/repo commit for some arbitrary time in the future.
