### ISSUE TITLE
Repo updating using git pull

### ISSUE THREAD

**Issue by FriendlyNeighborhoodShane** [kisslinux/kiss#168]
I think changing `git fetch; git merge;` for `kiss u` to the largely equivalent `git pull;` would allow using the `pull.rebase` config option in repos, making maintaining modifications to upstream repos far less of a PITA.

**Comment by dylanaraps** [comment]
For reasons I could not figure out, using `git pull` causes signature verification to break. I'll see if I can still reproduce the issue, if not I'm happy to make this change. :+1:

**Comment by FriendlyNeighborhoodShane** [comment]
If it is still breaking, perhaps an environment flag variable, or even a git config check to use rebase instead of merge would be viable?

**Comment by dylanaraps** [comment]
Made the change. Seems to work fine. :+1:
