### ISSUE TITLE
Feature request: configuration prompt intermediate

### ISSUE THREAD

**Issue by Sweets** [kisslinux/kiss#171]
Some packages may benefit from being able to customize specific files before the actual build process is done by the package manager (see: [st](https://github.com/kisslinux/repo/tree/master/xorg/st)).

For packages such as this, perhaps there could be a function in `kiss` that would be place in the `build` files that would allow the package to prompt a user if they wish to edit the files of the package before it's built?

`st/build`
```
#!/bin/sh -e

sed -i 's|Liberation Mono|Monospace|g' config.def.h

# Install terminfo to right location.
export TERMINFO=$1/usr/share/terminfo
mkdir -p "$TERMINFO"

configprompt # prompts user to modify configuration files
make
make PREFIX=/usr DESTDIR="$1" install
```

```
-> Do you wish to modify any configuration files before building st? [y/n]
y
```

Then have it have some way of selecting which file gets modified (or maybe its hardcoded to let users modify things like `config.h`, `configure.ac`, etc) and open the file in `$EDITOR`.

**Comment by mcpcpc** [comment]
Curious... why would this be preferred over the current practice of custom repos or package forks?  Seems like added complexity for a feature that (to some degree) exists already but with lack of traceability/reproduceability.

**Comment by Sweets** [comment]
It doesn't always make sense to create a custom repository, especially in one-off packages.

You may not necessarily want to have a custom repo just for one package. That implies that the user has to make the repository themselves, do the package management and maintain it for the single package they want to have a custom configuration for (when the package may already be packaged, and is maintained), and adds more to the `KISS_PATH`.

Also, the functionality may not necessarily be that which I pointed out in the original comment. Perhaps just some way to supply a custom configuration would be better than prompting the user to edit all the time, or maybe a path that is dedicated only to user configurations for a specific package. On that, I'd like you to point me in the direction of the feature that to some degree already exists, because I've not found it. I suppose a way to reimplement something of this would be to download sources before building, but for that much, a simple convenience function placed within the automated downloading in `kiss b` could supplement with much less user headache.

**Comment by jedahan** [comment]
I could imagine a `KISS_PATCH_PATH` which would allow a user to create a repository of just patches. Seems a bit difficult to manage though.

**Comment by mcpcpc** [comment]
> You may not necessarily want to have a custom repo just for one package. 

Makes me wonder how many people are running the core repos (+community) without custom packages?

> That implies that the user has to make the repository themselves, do the package management and maintain it for the single package they want to have a custom configuration for (when the package may already be packaged, and is maintained), and adds more to the `KISS_PATH`.

`kiss-fork` makes package customization fairly easy and straight forward, IMO.  Furthermore, by keeping all custom package/repository paths localized to `KISS_PATH`, it keep the static package management system truly “static” and sourceable.  

> On that, I'd like you to point me in the direction of the feature that to some degree already exists, because I've not found it.

The feature you desire does not exist, but the end result can be accomplished in a minimal number of commands (e.g. assuming you have a custom config.h file for st, `kiss-fork st`, `mkdir ~/repopath/st/files`, `cp ~/config.h ~/repopath/st/files`, `echo “files/config.h” > ~/repopath/st/sources`).  

I understand your need but, to me, this might be better as a supporting script and included as part of the wiki (for those desiring the added functionality)?

**Comment by dylanaraps** [comment]
> For packages such as this, perhaps there could be a function in kiss that would be place in the build files that would allow the package to prompt a user if they wish to edit the files of the package before it's built?

This isn't possible as the `build` files can be written in anything. The only requirement is that they be executable. The package manager doesn't source the build scripts (as is the case with `makepkg`, `abuild`, `xbps-src`, etc, etc), it instead treats them as any other executable (`./build <arg> <arg>`).

I can see a few ways to solve this.


**Package manager hook**

A package manager hook can be used to more or less implement this feature. This of course requires setup though it can be documented on the website to be accessible information to users. You can read all about how hooks work here: https://k1ss.org/package-manager#6.0

This could also be setup to look for specific files in some directory structure (`/path/to/kiss-configs/<PKG>/<FILE>`).

```sh
case $TYPE in
    pre-build)
        case $PKG in
            st)  cp ~/dotfiles/st/config.h . ;;
            dwm) cp ~/dotfiles/dwm/config.h . ;;
        esac
    ;;
esac
``` 

**Forking the package**

The user can fork the package into their own repository to make the desired changes. This is the most flexible solution though it may come with a varying degree of maintenance burden. Using `kiss link` can most of the time solve this maintenance issue by symbolically linking unchanged files to their original repository locations.

```sh
cd /path/to/my_repo
kiss fork st
...
``` 

**Adding config.h to files/**

This is an extension to the above solution and assumes that the package has the `config.h` (or config file) in `files/` (and therefore  a reference in the `sources` file). Following the same above steps, fork the package into your repository. From here, run `kiss link <file>` for every file which **is not** the `config.h`. The end result will look like this (link locations will differ depending on repository configuration):

```sh
st
├── build -> /home/dylan/projects/repo/xorg/st/build
├── checksums
├── depends -> /home/dylan/projects/repo/xorg/st/depends
├── files
│   └── config.h
├── sources -> /home/dylan/projects/repo/xorg/st/sources
└── version -> /home/dylan/projects/repo/xorg/st/version
```

As the files are linked, whenever the original `st` package receives an update, your own package will too. The `checksums` file cannot be linked as its contents differ from the original package. This brings the maintenance burden down to a `kiss c` when needed.
