### ISSUE TITLE
Add option to remove files in `/etc` in `kiss remove`

### ISSUE THREAD

**Issue by Rio6** [kisslinux/kiss#181]
Sometimes when testing and reinstalling packages, it's useful to remove all its files, even the ones in `/etc` to test a clean install. Adding an option or environment variable to for that would be helpful.

**Comment by jedahan** [comment]
not to be too clever, but if we do this, it would be nice if possible to checksum and warn if the original install file had been modified (perhaps showing the diff)

**Comment by dylanaraps** [comment]
Let me know your thoughts: https://github.com/kisslinux/kiss/pull/186
