### ISSUE TITLE
some kiss subcommands (e.g. install, update) do not like hyphens in $KISS_PATH

### ISSUE THREAD

**Issue by carlosdavidepto** [kisslinux/kiss#184]
While trying to do a clean install, I hit the following issue:

    $ kiss u
    -> Updating repositories
    /usr/bin/kiss: cd: line 1246: can't cd to /home/davide/kiss-repos/repo/core: No such file or directory
    $ echo $KISS_PATH
    /home/davide/kiss-repos/repo/core:/home/davide/kiss-repos/repo/extra:/home/davide/kiss-repos/repo/xorg:/home/davide/kiss-repos/community/community

kiss b gnupg1 was also failing, but with a different error:

    ERROR Package 'gnupg1' not in any repository
    -> Building: gnupg1
    -> gnupg1 Checking repository files
    ERROR Package 'gnupg1' not in any repository
    ERROR Version file not found

repo and community were previously checked out successfully to those paths, and a simple `mv kiss-repos kissrepos` and adjusted $KISS_PATH worked around the problem.

**Comment by dylanaraps** [comment]
I cannot reproduce this issue. I could only reproduce it when my `KISS_PATH` had a mismatch with the real name of the directory. Please ensure that your `KISS_PATH` is set correctly.

**Comment by carlosdavidepto** [comment]
I just tried again on a fresh chroot from the same tarball and can't replicate the behavior either.

I double checked the paths, visually and using ls with the paths shown in the text above (copied and pasted). Must have been something a bit more obscure, but at the time it did not occur to me to run the file through hexdump or something similar, and I don't have the problematic environment file anymore to check now.

I'll reopen with more details if I see this problem again.
