### ISSUE TITLE
Unable to fetch source: 406 - not acceptable

### ISSUE THREAD

**Issue by sdsddsd1** [kisslinux/kiss#188]
Hey,
I have a source which can be downloaded through wget and firefox but not within 'kiss'. It errors out with `curl: (22) The requested URL returned error: 406 Not Acceptable` . Its probably a shitty source, but the only one which bundles this assets in an easily extractable way. Maybe you have an idea how to workaround this?

http://srb2.thewaitingroom.org/srb2kart-v101-full-linux.zip

**Comment by dylanaraps** [comment]
The link works fine here. Try: `/etc/ssl/update-certdata.sh`

**Comment by sdsddsd1** [comment]
No luck with that. I must say that this source worked some months ago on my end too.

**Comment by sdsddsd1** [comment]
For completeness: sb could reproduce the issue https://freenode.logbot.info/kisslinux/20200916#c5126455 . 
It seems that the source is somewhat faulty.

**Comment by konimex** [comment]
I can reproduce it with my curl. Had to bypass it using a user agent like in your link.

**Comment by dylanaraps** [comment]
I think it's best we find a mirror that plays nice with curl rather than forcing a user agent to workaround the issue.
