### ISSUE TITLE
`kiss version <pkg>` should give the package version of `<pkg>`

### ISSUE THREAD

**Issue by noocsharp** [kisslinux/kiss#189]
To me, it would make sense for `kiss version <pkg>` to give the version of the package `<pkg>`, and give the version of the package manager when provided with no arguments. Thoughts?

**Comment by dylanaraps** [comment]
`kiss list pkg` exists for this purpose. You can also read from the database directly.

```sh
read -r ver rel < /var/db/kiss/installed/<pkg>/version

printf '%s %s\n' "$ver" "$rel"
```
