### ISSUE TITLE
KISS should not check for make dependencies in target root

### ISSUE THREAD

**Issue by konimex** [kisslinux/kiss#19]
When building a new, empty `KISS_ROOT` (e.g. `/kiss`, henceforth referred to as "target"), the package manager should not check the `make` dependencies in the target `kiss` database (e.g. `/kiss/var/db/kiss`), but only check the `make` dependencies in the old root with a full KISS environment (e.g. `/` with database in `/var/db/kiss`, henceforth referred to as "host"). Since when building target we're using binaries from the host, any `make` dependencies from the target `KISS_ROOT` won't be used.

However, if the host is not a `kiss` system, we would have to rely on their packaging system (e.g. I had to use `apk` from Alpine to install `m4` for `bison` makedepends)

**Comment by dylanaraps** [comment]
Could add an environment variable to skip dependency checks. Would this solve the issue?

**Comment by konimex** [comment]
If we rely on an outside system (e.g. Alpine in `kiss-chroot-0.0.1`), then it shouldn't be a problem. But I believe if we're bootstrapping another KISS system from a host KISS system, I believe we should take advantage of the existing `depends` system.

**Comment by dylanaraps** [comment]
I think we should just base building a `chroot` on an existing one (*running `KISS_ROOT=bla kiss` from an existing `kiss` `chroot`*). I don't think this is an easily solvable problem as there's no universal way to communicate with the host (whatever OS the host may be).
