### ISSUE TITLE
dynamically set prefix.

### ISSUE THREAD

**Issue by FultonBrowne** [kisslinux/kiss#191]
Add a dynamic prefix variable (let's say KISS_PREFIX). This would allow users and other distro's to:

1. Set the main prefix to / instead of /usr

2. Set secondary namespace similar to [stali linux](https://sta.li/filesystem/)

This change would probably require stuff like this:

`./configure 
--prefix="/usr"
` 

to change to this:

`./configure 
--prefix="$KISS_PREFIX"
`

**Comment by dylanaraps** [comment]
Added this feature here: https://github.com/kisslinux/kiss/commit/e070753d7b6873b32389a62ec16fae6ea592108a

This is less of a code change and more of a "best practices" / "style guide" one as it's mostly just changing `/usr`, etc to environment variables in build files (and then getting everyone to do it from then on). Package manager just sets default values for them if empty and uses them to fix a few hard-coded paths.

Also added `KISS_LIBDIR` and `KISS_DATADIR` though others are probably required (package manager needed these ones).
Try it out and let me know your thoughts. Let me know if other environment variables are needed too.

Note: Feature will likely change before release or it might not be kept around. Need to think about it some more.

**Comment by dylanaraps** [comment]
E5ten (in IRC) suggests changing the default values (except for `_PREFIX`) to drop the leading `/`.  https://github.com/kisslinux/kiss/commit/a129610f24c20c9b0a710a64ea32d280be8a30af 

Also changed to allow `_PREFIX` to be set to `''` (for `/`). https://github.com/kisslinux/kiss/commit/cf65299d429d69a119fffa81b5c1f59fba0a1833

**Comment by dylanaraps** [comment]
Note: There are also changes to be made to `contrib/`

**Comment by dylanaraps** [comment]
Decided against this. See discussion in IRC here: https://freenode.logbot.info/kisslinux/20200927#c5255439
