### ISSUE TITLE
Symlinks created in /etc get ignored by KISS

### ISSUE THREAD

**Issue by git-bruh** [kisslinux/kiss#193]
If the build script creates a symlink in /etc, it doesn't get created when the package is installed by KISS. However, the file is present in the tar and is tracked in the manifest aswell. The symlink creation works fine if it's in another directory like /var

Example:
```
#!/bin/sh -e

install -d "$1/etc/test"
ln -s test "$1/etc/testlink"
```

This was addressed in #112 but seems to be broken again.

**Comment by git-bruh** [comment]
Needs to be fixed again

`6.0.0`: Works
`5.2.0`: Broken
Latest Master: Broken

**Comment by dylanaraps** [comment]
Am on it. Thanks for letting me know.

**Comment by dylanaraps** [comment]
Please try the latest master and let me know if the issue is resolved.

**Comment by git-bruh** [comment]
Symlinks get created just fine, but if the package is removed, they get skipped even though none of the files that the links point to have been modified (This seems to be present in `6.0.0` aswell)

```
Skipping /etc/alsa/conf.d/98-usb-stream.conf (modified)
Skipping /etc/alsa/conf.d/60-vdownmix.conf (modified)
Skipping /etc/alsa/conf.d/60-upmix.conf (modified)
Skipping /etc/alsa/conf.d/50-pulseaudio.conf (modified)
Skipping /etc/alsa/conf.d/50-oss.conf (modified)
Skipping /etc/alsa/conf.d/50-arcam-av-ctl.conf (modified)
Skipping /etc/alsa/conf.d/10-speexrate.conf (modified)
```

Package is `alsa-plugins`

**Comment by dylanaraps** [comment]
Thanks, this is another bug. Will fix it in a couple of minutes. :+1:

(Will also push a release once I'm done solving a couple of other things)

**Comment by dylanaraps** [comment]
Pushed 1/2 commits to fix this second issue.

**Comment by dylanaraps** [comment]
OK. So I cannot at present fix this <specific> issue without major refactoring of the `pkg_remove_files` function. The files `alsa-plugins` installs to `/etc/` are symlinks to files in `/usr/share/`. When the package is removed, the files in `/usr/share` are removed first. This turns the files in `/etc/` into broken symlinks which causes them to fail the checksum verification.

Anyway. Will get onto doing this soon. The present situation isn't bad (message is displayed when file is skipped so you can look into it yourself). For the C rewrite of the package manager, this shouldn't be an issue at all.

**Comment by git-bruh** [comment]
:+1: Thanks for looking into it

**Comment by dylanaraps** [comment]
(Pushed a new release also, not sure if you have noticed or not)
