### ISSUE TITLE
Several issues with latest master

### ISSUE THREAD

**Issue by dilyn-corner** [kisslinux/kiss#194]
In order of urgency: 

1) when running `kiss u`, if the list of packages to update is >1, `kiss` will fail after building the first package and reports that 'pkg2 has not been built'. To reproduce: download latest kiss-chroot tarball, install latest `kiss` script/clone official repo (git clone bla bla), and run `kiss u`. It will report that `binutils`, `bison`, and `git` are to be updated. Hitting enter at the prompt will result in `binutils` being built and installed, and it will erorr out at `bison` reporting the aforementioned error. Repeating `kiss u` will reproduce the same problem, failing at `git`. 

2) when building a package, `kiss` will prompt to install built packages, and reinstall all built packages. That is to say, `kiss b foo` will prompt to build `bar`, `baz` as make dependencies of `foo`. After building `foo`, `kiss` will prompt to install the built packages [`bar` `baz` `foo`] and will reinstall `foo`, `bar`, and `baz`. To reproduce, do `kiss b automake` with `autoconf`, `perl` not installed. This happens for packages besides `automake`. 

3) `kiss` will sometimes fail to properly execute build order. This happens in an unreproducible way; if `foo` has dependencies which need to be built, `kiss` will sometimes fail to build the packages in the correct order. It doesn't seem tied to any particular package, any particular dependency chain, or any particular package in the dependency chain. For instance, it (literally just) happened when I attempted to `kiss b plasma-desktop` from a fresh kiss-chroot - it failed to download and build `cmake`, even though it reported it in the list of packages to be built/installed, and `extra-cmake-modules` failed to build because `cmake` was missing. It has previously happened for many other packages I have attempted to build, and is almost always resolved after a second `kiss b` (and always solved after a third). _NOTE_ this issue has persisisted for me for... a long time, and is not necessary related to `kiss` 6. Just something you might want to peak at.

**Comment by dylanaraps** [comment]
Thanks. Been a little busy this week. Will get around to fixing these soon. If there are any urgent bug fixes needed for current release I can back-port them.

**Comment by dilyn-corner** [comment]
Totally fine that you're busy! Just wanted to make sure these issues got looked at before you pushed the change. 

To go with (3), it might just be the case that the first package gets ignored? I'll work on confirming this suspicion, but from a build I just attempted it seems like this might be the case. 

This part can always be a continued issue to look at; from my perspecitve, it doesn't stop the release of kiss6.

**Comment by dylanaraps** [comment]
Number 2 in the list has been fixed.

**Comment by dilyn-corner** [comment]
Can confirm that 2 has been fixed. 1 remains unresolved.

**Comment by sdsddsd1** [comment]
This issue is related to number 3.   
It _seems_ that ´xorg-server´ was tried to build after a "base installation".
https://github.com/kisslinux/repo/issues/221

**Comment by dylanaraps** [comment]
Backported the important stuff: https://github.com/kisslinux/kiss/releases/tag/5.2.0
