### ISSUE TITLE
latest release no version for meson

### ISSUE THREAD

**Issue by muevoid** [kisslinux/kiss#195]
I'm not sure if this is an issue with kiss or repo. However I have tried using my own meson build and the official repo however the same error always happens. '/meson/version' not found. However I have checked all repos in KISS_PATH tried removing all except for core repos and community. There is indeed a version file I have checked in repo/extra/meson/version and /var/db/kiss/installed/meson/version. Both exist and are not symlinks and contain the correct version. Im not sure where to trouble shoot from here.

**Comment by dylanaraps** [comment]
I can't reproduce at all. Send me the package manager output.

**Comment by dylanaraps** [comment]
Is this about the 6.0.0 pre-release or 5.X.X?

**Comment by muevoid** [comment]
5.1.0

**Comment by muevoid** [comment]
Also the ouput only says.
```
Check repository file.
version file not found
```

**Comment by dylanaraps** [comment]
That would be this code: https://github.com/kisslinux/kiss/blob/f915d9aebc6a0452152f9335d295c88be503f6e5/kiss#L114-L123

**Comment by dylanaraps** [comment]
Send me the output of `ls -l` inside the `meson` repository directory.

**Comment by muevoid** [comment]
output of ls -l in meson directory
```
-rwxr-xr-x    1 poppiroz poppiroz    116  Oct 17  15:14 build
-rw-r--r--       1 poppiroz poppiroz    65    Oct 17  15:14 checksums
-rw-r--r--       1 poppiroz poppiroz    15    Oct 17  15:14 depends
-rw-r--r--       1 poppiroz poppiroz    58    Oct 17  15:14 sources
-rw-r--r--       1 poppiroz poppiroz    9      Oct 17  17:10 version
```
output of cat version
```
0.55.3 2
```

**Comment by dylanaraps** [comment]
Try removing the `2>/dev/null` found here: https://github.com/kisslinux/kiss/blob/f915d9aebc6a0452152f9335d295c88be503f6e5/kiss#L114-L123

**Comment by muevoid** [comment]
/usr/bin/kiss: line 118: can't open version: no such file
ERROR Version file not found

**Comment by dylanaraps** [comment]
What's the output of `kiss s meson`?

**Comment by muevoid** [comment]
This was completely user error doh. I don't know how but on her computer she had a file in / called meson which somehow was in KISS_PATH. I have no clue how this happened. We both say thank you for the help. I will close this issue.
