### ISSUE TITLE
same filenames in sources issue

### ISSUE THREAD

**Issue by Koboldthegreat** [kisslinux/kiss#196]
I came across a caching issue when packaging opencv.

my `opencv/sources` file contains:
```
https://github.com/opencv/opencv/archive/4.5.0.tar.gz 
https://github.com/opencv/opencv_contrib/archive/4.5.0.tar.gz contrib
```

Because the source files have the same filename it seems kiss does not differentiate between those 2 files, mapping both file sources to the same archive (the first one) when checking for cached sources. This results in the same archive extracted in `$1/` and `$1/contrib/` folder, instead of the first one in `$1/` and the second archive in `$1/contrib`

**Comment by dylanaraps** [comment]
Note: This will invalidate sources which currently use `dest` and these files will be re-downloaded. The cache can also be updated using the script below.

```sh
#!/bin/sh

set -ef

cac_dir=${XDG_CACHE_HOME:-$HOME/.cache}/kiss/sources

kiss l | while read -r pkg _; do
    cd $(kiss s "$pkg")

    [ -f sources ] || continue

    while read -r src dest || [ "$src" ]; do
        [ "$dest" ] || continue
        [ -f "$cac_dir/$pkg/${src##*/}" ] || continue

        mkdir -p "$cac_dir/$pkg/${dest:-.}"

        mv -f "$cac_dir/$pkg/${src##*/}" \
              "$cac_dir/$pkg/${dest:-.}/${src##*/}"

        printf '[%s] fixed %s -> %s\n' \
            "$pkg" "${src##*/}" "${dest:-.}/${src##*/}"
    done < sources
done
```
