### ISSUE TITLE
Remote compiling support

### ISSUE THREAD

**Issue by dev-kittens** [kisslinux/kiss#206]
hi! is it possible to tell KISS to build on a remote host? I am not familiar with the relevant technology, but the simplest thing as an user would probably be to give the package manager a SSH target with the kiss utilities installed.
otherwise, is it possible to build a package on one machine, then export the resulting binaries to import (and install) on another machine?
thank you very much!

**Comment by jedahan** [comment]
Might wanna look at distcc? https://distcc.github.io/

**Comment by dylanaraps** [comment]
> hi! is it possible to tell KISS to build on a remote host?

No. This is best left to external tooling and not something directly supported.

> otherwise, is it possible to build a package on one machine, then export the resulting binaries to import (and install) on another machine?

Built packages exist in `~/.cache/kiss/bin`. So long as the architecture matches and `-march=` was not used in `CFLAGS`, you can install these packages on other systems. Either via copy/paste to the remote's cache directory or `kiss i /path/to/tarball`.

**Comment by dev-kittens** [comment]
thank you very much!

**Comment by jedahan** [comment]
Something I’ve mulled around for a bit is creating an OCI image for kiss. That might make it possible to use GitHub actions or gitlab CI or the sourchut equivalent to spit out reproducible-ish binaries that can be installed like Dylan describes
