### ISSUE TITLE
kiss install unnecessary root permissions?

### ISSUE THREAD

**Issue by jedahan** [kisslinux/kiss#210]
I noticed that my repos are installing as root when merging into the filesystem (using https://github.com/jedahan/kiss-repo-repos ). I am wondering if this is a side effect of me setting /bin/sh to bash (using kiss alternatives) or something else.

**Comment by ricardoG08** [comment]
During the update of KISS Linux (following the installation guide) it shows me that the `KISS_SU` variable is invalid, for a temporary solution I do the following:

`# KISS_SU=su kiss update`

**Comment by dylanaraps** [comment]
Root permissions are used only required when they're required. Sounds to me like some permissions issue with your files.
