### ISSUE TITLE
Failed to generate checksums

### ISSUE THREAD

**Issue by 0yQXYNAUKEA0EFbZy3OyNXQNCiVlNbDv1z0Ry6A** [kisslinux/kiss#220]
-> dhcpcd Generating etcsums
ERROR Failed to generate checksums for '/root/.cache/kiss/proc/10394/pkg/dhcpcd/etc/sv/dhcpcd/supervise'

-> busybox Generating etcsums
ERROR Failed to generate checksums for '/root/.cache/kiss/proc/11006/pkg/busybox/etc/sv/acpid/supervise'

Seems like it affects every package that has something to do with supervise.

kiss version: 5.4.4

**Comment by dylanaraps** [comment]
Pushed a new package manager release. Thanks.
