### ISSUE TITLE
Problem with copying files

### ISSUE THREAD

**Issue by 0yQXYNAUKEA0EFbZy3OyNXQNCiVlNbDv1z0Ry6A** [kisslinux/kiss#221]
Seems kiss doesn't copy files at all now.

kiss b opendoas
cat /etc/doas.conf
cat: can't open '/etc/doas.conf': No such file or directory

kiss b dhcpcd
ls /etv/sv/dhcpcd 
empty

Can you reproduce the issue?

**Comment by dylanaraps** [comment]
I can't reproduce at all. Is this only files in `/etc/`?

**Comment by dylanaraps** [comment]
I can reproduce.

**Comment by dylanaraps** [comment]
Pushed a new release which fixes this issue. Thanks again.
