### ISSUE TITLE
fails to extract .tbz source

### ISSUE THREAD

**Issue by sdsddsd1** [kisslinux/kiss#227]
kiss fails to extract https://downloads.sourceforge.net/project/cnibbles/Source/cNibbles%20v2.0.1/cNibbles-2.0.1.tbz with `short read`.
Earlier(much earlier) versions could handle this source.

**Comment by dylanaraps** [comment]
Fixed, thanks.

Has this ever worked? I don't recall ever supporting `.tbz` files.

**Comment by sdsddsd1** [comment]
I _think_ it must have. Because this is one of my earliest packages. Otherwise it would not have been there.

**Comment by dylanaraps** [comment]
Will push a release once I've confirmed that #226 is fixed. Just waiting on a response.

**Comment by sdsddsd1** [comment]
Ahhhh,
you are right. You obviously never supported .tbz. https://github.com/sdsddsd1/kiss-games/blob/master/games/cnibbles/build#L3
But I dont recall kiss ever failing. Nevermind, now its implemented :D
