### ISSUE TITLE
cannot install new package since 5.4.3 release

### ISSUE THREAD

**Issue by fanboimsft** [kisslinux/kiss#228]
when trying to install a new package I get the following error since the 5.4.3 update:

kiss i pango
-> pango Checking if manifest valid
-> pango Checking if package installable
-> pango Checking for package conflicts
/usr/bin/kiss: line 892: cd: /var/db/kiss/installed/pango: No such file or directory

root [ ~ ]# mkdir -pv /var/db/kiss/installed/pango
mkdir: created directory '/var/db/kiss/installed/pango'
root [ ~ ]# kiss i pango
-> pango Checking if manifest valid
-> pango Checking if package installable
-> pango Checking for package conflicts
/usr/bin/kiss: line 892: cd: /usr/include/pango-1.0/pango: No such file or directory

root [ ~ ]# mkdir -pv /usr/include/pango-1.0/pango
mkdir: created directory '/usr/include/pango-1.0'
mkdir: created directory '/usr/include/pango-1.0/pango'
root [ ~ ]# kiss i pango
-> pango Checking if manifest valid
-> pango Checking if package installable
-> pango Checking for package conflicts
-> pango Installing package (pango@1.48.5-1.tar.gz)
-> pango Verifying installation
-> pango Installed successfully

system is running glibc/coreutils

**Comment by dylanaraps** [comment]
Does this issue still occur with the latest release (`5.4.11`)?

**Comment by dylanaraps** [comment]
Let me know if the issue still occurs. I cannot reproduce this at all.

**Comment by fanboimsft** [comment]
Issue was still present in 5.4.11 but is fixed with acc1a22475f07a29cb00a424f940eccc40666297 

Thanks!

**Comment by dylanaraps** [comment]
No problem. Just waiting to hear word about this issue (https://github.com/kisslinux/kiss/issues/226) and I'll push a new release.
