### ISSUE TITLE
Additional hook types and information to expose

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/kiss#234]
- What information would you like exposed to hooks?
- Are there any other places in the package manager you would like to hook into?

**Comment by jedahan** [comment]
I will try and keep each feature request in a separate comment, so its easier to comment on.

---

I would like a `post-update` hook for repository pulls. The full path to the updated repository, plus the commit hash for before and after would be convenient (though maybe the "before" commit hash should be in a `pre-update` hook).
The use case would be for me to aggregate and show a summary of whats changed via git log, something like [kiss-log](https://github.com/jedahan/kiss-repo/blob/main/kiss-log/files/kiss-log).

**Comment by dylanaraps** [comment]
All you need is the full path. On pre-update you can grab the first hash and on post-update the second. The git commit information is nothing unobtainable outside of the package manager so I don't think it should expose it.

**Comment by dylanaraps** [comment]
We need to also document the hook types and their arguments/environment so scripts know what they're given.

**Comment by dylanaraps** [comment]
Simplified the hook code further. Now supports any number of arguments to hooks (and the arguments are generic).

https://github.com/kisslinux/kiss/blob/master/kiss#L110-L119

**Comment by jedahan** [comment]
Nice! I have a sketch of a hook that uses this up https://github.com/jedahan/kiss-repo/pull/5/commits/7f317bff1356107cededb0969b816f678897adfe

**Comment by dylanaraps** [comment]
You can just do:

```sh
case $1 in
pre-update)
    # This works as $PWD == $2.
    pre-hash=$(git rev-parse HEAD)
;;

post-update)
    post-hash=$(git rev-parse HEAD)
;;
esac
```

The hook only executes **once per git repository** also. There's no need for you to filter any duplicates. We could omit passing an argument altogether documenting that the `update` hooks are executed in the repository itself.

**Comment by dylanaraps** [comment]
Hooks are documented here: https://kisslinux.xyz/package-manager#6.1

This should prevent misuse and add clarity. Closing this issue as I'm happy
with how these are for now (and I want to push a release today).

We can expand this over time. I'm out of ideas for now anyway. ;)

Thanks for the help.
