### ISSUE TITLE
Library issue

### ISSUE THREAD

**Issue by f1nniboy** [kisslinux/kiss#236]
I just upgraded to KISS `5.5.2` and `dhcpcd` & `pigz` fail to build because they cannot find some system libraries. (`stdio.h`, `assert.h`, etc.)

**Comment by dylanaraps** [comment]
Send a log. They build fine here.

**Comment by f1nniboy** [comment]
https://dpaste.com/CNEQLY3LJ

**Comment by dylanaraps** [comment]
Do they build if you clear your CFLAGS? `CFLAGS= kiss b pigz dhcpcd`?

**Comment by dylanaraps** [comment]
Do the files exist in `/usr/include`? (`/usr/include/sys/stat.h`)

**Comment by dylanaraps** [comment]
Do the files exist in `/usr/include`? (`/usr/include/sys/stat.h`)

**Comment by dylanaraps** [comment]
Do the files exist in `/usr/include`? (`/usr/include/sys/stat.h`)

**Comment by f1nniboy** [comment]
Yes. It looks like this is an issue with WyverKISS because these packages build fine with the normal KISS rootfs.

**Comment by konimex** [comment]
Open an issue there, I'll take a look.
