### ISSUE TITLE
kiss-fork sometimes includes a manifest

### ISSUE THREAD

**Issue by dilyn-corner** [kisslinux/kiss#239]
In instances where `foo` is only in `/var/db/kiss/installed`, `kiss-fork` will copy every file including the `manifest`. 

Nonfatal, just a nit.

**Comment by dylanaraps** [comment]
This is intended behavior. It copies the directory from the first repository verbatim to your current directory. The installed database *is* another repository it just also contains some metadata (manifest, etcsums).

I *could* add an `rm -f manifest etcsums` line to the utility but it seems pointless (and partially ties the tool to the package format). Thanks
for the issue.
