### ISSUE TITLE
Issue downloading some packages with new sources parsing

### ISSUE THREAD

**Issue by dilyn-corner** [kisslinux/kiss#242]
This is just a super cute little bug that exists for... A single package, due to dubious naming choices by the developer.

Caused by https://github.com/kisslinux/kiss/blob/b7b57bd34caf2135f8fe6c940a4a9d554ac0f365/kiss#L337

Problematic package is `libsodium` https://github.com/kiss-community/community/blob/main/community/libsodium/sources

It's a literal "RELEASE", not to be substituted.
I'd probably just rename RELEASE to EPOCH or RELVER.

**Comment by dylanaraps** [comment]
Oh that's funny!

On it.

**Comment by dylanaraps** [comment]
There are other download URLs here for reference: https://download.libsodium.org/libsodium/releases/

Example: https://download.libsodium.org/libsodium/releases/libsodium-1.0.18.tar.gz

**Comment by dylanaraps** [comment]
Pushed a different fix. Kept `RELEASE` as-is, added ability to start a source with `raw:` to disable all marker replacements. Also, there's a workable source above. **If** many conflict issues with URLs exist, we can look into making the markers more unique (I don't think this will be the case). The `raw:` addition also gives users the means to make a source work despite conflict issues with markers (if they occur).

**Comment by dilyn-corner** [comment]
Thanks Dylan!

**Comment by dylanaraps** [comment]
I'll look into how feasible `\MARKER` is for problematic sources (ie, simple escaping rather than ugly `raw:`) (Then things can remain fully functional in all cases - just escape the conflicting marker and the others will work).

**Comment by dylanaraps** [comment]
Added support for escaping markers, see: https://github.com/kisslinux/kiss/commit/83c88b4222f1787ed4f9f05061a5e583ee7b45ce
