### ISSUE TITLE
ISSUE_TEMPLATE: specify path to kiss

### ISSUE THREAD

**Issue by sdsddsd1** [kisslinux/kiss#244]
## Description
`env KISS_PROMPT=0 sh -x kiss <arguments> > log 2>&1` does not work.
should prob be `env KISS_PROMPT=0 sh -x /usr/bin/kiss <arguments> > log 2>&1`

The content of `log` says 
```
sh: can't open 'kiss': No such file or directory
```

**Comment by dylanaraps** [comment]
It works fine here. Cannot reproduce.

Besides, the command is an example. Users need to modify it when submitting reports anyway.

**Comment by dylanaraps** [comment]
Made the change, thanks.
