### ISSUE TITLE
${@:?} isn't portable

### ISSUE THREAD

**Issue by illiliti** [kisslinux/kiss#257]
This breaks mksh:

https://github.com/kisslinux/kiss/blob/554462faa7556f954dedcd0eeb6efd48ae95ab5b/kiss#L1843

Issue 8(draft) of POSIX clearly defines that expansions of $@/$* result in undefined behavior:

https://www.austingroupbugs.net/view.php?id=1478

**Comment by dylanaraps** [comment]
https://github.com/kisslinux/kiss/commit/bb98906055dc88e68eabe92f4ea9a94407a5b4ca

Missed this issue. Was already fixed before you opened it anyway. :)
