### ISSUE TITLE
Empty dirs in .cache/kiss/proc when not using KISS_DEBUG, randomly don't get deleted

### ISSUE THREAD

**Issue by kyx0r** [kisslinux/kiss#259]
- [?] Does this issue occur in master?
Probably yes, tested on 5.5.25

When performing sequence kiss b && kiss i and KISS_DEBUG being unset empty pid named dirs randomly don't get deleted resulting in useless clutter. Also confimed by GalaxyNova and testuser on irc.

**Comment by dylanaraps** [comment]
I cannot reproduce. Does it happen with specific packages or is it totally random?

**Comment by konimex** [comment]
I can confirm this. It's totally random. I think it might be related with `kiss u`?

**Comment by kyx0r** [comment]
Oh I think I know now, this confusion might be caused by doing something like this:

```ki() { export KISS_PROMPT=0 && kiss b "$1" && kiss i "$1" && unset KISS_PROMPT; }```

Because if prompt is disabled, kiss b will try to install package and fallthough and then another command kiss it will install it again. So obviously we can fix that shell function, however what is interesting, it creates 2 pid dirs in /proc and one of them will not get deleted for some reason and every dir inside will be empty.

So it turns out that ```kiss install``` leaves those junk directories behind when KISS_DEBUG=1
Perhaps it's the only problem, or maybe there are other reasons when sometimes ```kiss install``` gets bugged

**Comment by dylanaraps** [comment]
>  however what is interesting, it creates 2 pid dirs in /proc and one of them will not get deleted for some reason and every dir inside will be empty.

Two directories are created because two instances of the package manager are launched.

> So it turns out that kiss install leaves those junk directories behind when KISS_DEBUG=1

Yes, this is intentional.

>  Perhaps it's the only problem, or maybe there are other reasons when sometimes kiss install gets bugged

I still cannot reproduce using your function. Your function ends up installing the package twice no? If you disable the prompt the package will be automatically installed after `kiss b`, you then run `kiss i` afterwards(?).

**Comment by kyx0r** [comment]
Yes I think in my case I just had a bugged function in my .rc because of blundering the fact that the package will be installed twice (which is wrong). But I don't know how other people are running into this problem.

**Comment by dylanaraps** [comment]
A log file (containing the failure to clean the cache) would be great if anyone is able to obtain one.

**Comment by dylanaraps** [comment]
What `KISS_` environment variables do you have set by the way?

**Comment by dylanaraps** [comment]
Also, with these leftover directories who is the owner and what are the permissions? (`ls -ld dir`).

**Comment by dilyn-corner** [comment]
I can reproduce this issue. The directories are owned by me, none of the files inside exist (just the directories `kiss` makes), and here are the variables I have set: 
```
KISS_PATH=:/var/db/kiss/KISS-me/core:/var/db/kiss/KISS-me/extra:/var/db/kiss/KISS-me/wayland:/var/db/kiss/KISS-me/gpl
KISS_CHK=b3sum
KISS_TMPDIR=/tmp
KISS_SU=doas
KISS_COMPRESS=zst
KISS_HOOK=/home/dilyn/fossil/KISS-me/hooks
```

I'll see if I can find an obviously reliable way to reproduce this.

**Comment by dylanaraps** [comment]
If you can reproduce it reliably, a log file would be great.

**Comment by git-bruh** [comment]
This seems to happen when extensions are invoked via 'kiss cmd' instead of the real script 'kiss-cmd', like kiss fork

**Comment by dylanaraps** [comment]
Fixed. Thanks for finding the cause.
