### ISSUE TITLE
Feature request - list of explicitly installed packages (for better orphan handling)

### ISSUE THREAD

**Issue by LostGhost1** [kisslinux/kiss#262]
I feel like what's currently present in contrib/kiss-orphans, a hardcoded list of packages that are supposed to be there, won't do.

The list could be a text file /var/db/kiss/installed-explicit and it could contain names of packages line-by-line.

Arguments to "kiss build" would be attached to the list upon successful compilation, if not already present
Arguments to "kiss remove" would be removed from the list upon removal.

Seems simple enough, although I probably missed a few corner cases.

What do you think, dylan?

**Comment by FriendlyNeighborhoodShane** [comment]
The final result of the prototype in that PR is here: https://gist.github.com/FriendlyNeighborhoodShane/41593680b39c0c04cd82b5497ca25a26

It's not the solution to your exact request, but it serves all of my package-maintainance needs.
