### ISSUE TITLE
Make kiss build more scriptable

### ISSUE THREAD

**Issue by jedahan** [kisslinux/kiss#265]
- [x] Does this issue occur in master?

## Description

I would like to only build packages, not install.

This is for running a build server, testing, and scripting the package manager.

`KISS_PROMPT=0` will auto-install, and `kiss build somepackage` will wait for user input.

## Ideas

Ideally, `kiss build` would only build a package, and not prompt for install.

If `kiss install` did the equivalent of today's `KISS_PROMPT=0 kiss build` then we could remove that use case for `kiss install` which would simplify things and make `kiss` friendlier with other scripts.

**Comment by dylanaraps** [comment]
I may do what you suggest (build == build only).

**Comment by dylanaraps** [comment]
This commit should get you up and running for now at least.

**Comment by dylanaraps** [comment]
Pushed a less intrusive fix (at least for now). Simply making `KISS_PROMPT=0` skip the post-build prompt entirely.
