### ISSUE TITLE
Use the kiss package manager on arch

### ISSUE THREAD

**Issue by luis-07** [kisslinux/kiss#266]
I have to be on arch but I want to use the kiss package manager what I have to do to get kiss work?

**Comment by dylanaraps** [comment]
Install the necessary dependencies (https://kisslinux.org/package-manager#002) and set the environment variables accordingly (https://kisslinux.org/package-manager#003). Look at `KISS_ROOT` specifically.

**Comment by luis-07** [comment]
Thanks

**Comment by luis-07** [comment]
I get a error message line 164 xd /var/db/kiss/installed/base: init No such file or directory (when I am trying to build base init)

**Comment by dylanaraps** [comment]
Open a new issue filling out the template.
