### ISSUE TITLE
Hook for Ctrl+C

### ISSUE THREAD

**Issue by ioraff** [kisslinux/kiss#280]
I gather that `build-fail` only runs for SIGHUP as it's called via `||`. It would be nice to either have it (or a new hook type) be called by SIGINT, too, so it runs on Ctrl+C. Thanks.

**Comment by dylanaraps** [comment]
Implementing this helped me uncover a bug in `pkg_clean` where the call order is wrong (in reverse). Will fix this bug and then push the hooks and fix.
