### ISSUE TITLE
Discussion: Should package builds be ran from the driectory with the install and post-install scripts

### ISSUE THREAD

**Issue by godalming123** [kisslinux/kiss#306]
- [X] Does this issue occur in master?

## Description

When the packadge build files are ran they are ran from the directory you are in when you run kiss build. Should this be changed as it might be easier (for package maintainers & users) since downloaded files do not end up clogging the directory where the pckages are installed from and they can easily reference files in the packadge

**Comment by aabacchus** [comment]
Build scripts are run from a temporary directory contained the extracted sources. Post-install scripts are used for things like setting up users or rebuilding some system cache, or just writing a message, and shouldn't require access to a package's sources. What in particular do you want to do in the post-install script? It may be better suited to the build file.

**Comment by godalming123** [comment]
Yes this makes sense I just did'nt fully read the docs
