### ISSUE TITLE
mv files with extra privilages

### ISSUE THREAD

**Issue by godalming123** [kisslinux/kiss#307]
## Description

I am trying to package hyprland a wm for this I need to move files to privilaged directories like `/bin/`. This does not work since I do not have privilages. How can I say that my package needs root privilages in a way that works with any supported privilage system (`su`, `doas`, `sudo`)

**Comment by aabacchus** [comment]
Your build file should install to a hierarchy under a DESTDIR, and then kiss will be able to enumerate all the files owned by the package. Kiss itself will install files to their destination in /usr/bin. You should read https://kisslinux.org/wiki/package-system and perhaps the [style guide](https://kisscommunity.bvnf.space/kiss/style-guide/) and look at some other packages to get a feel for how this is done.

**Comment by godalming123** [comment]
So:
```
mv example-file $DESTDIR/usr/bin/
```
Would move the example file from the sources to the `/usr/bin` directory

**Comment by aabacchus** [comment]
Yes.

It looks like hyprland uses the meson build system, which will respect the DESTDIR variable if you use the install target it generates rather than moving files manually. Look at some other packages which use meson (or there's an example in the style guide).

**Comment by godalming123** [comment]
Thankyou
