### ISSUE TITLE
Fix how kiss handles invalid commands

### ISSUE THREAD

**Issue by naltun** [kisslinux/kiss#32]
Take this screenshot:
![image](https://user-images.githubusercontent.com/7507990/61805765-6c349b80-ae04-11e9-88d6-757c1c3fc01c.png)

`kiss` parses the argument `oniguruma` and assumes it is `kiss o`/aka `kiss owns`.

I actually meant to run `kiss i oniguruma`. In this circumstance, `kiss` should catch that I supplied an invalid command (`kiss [b|c|d|i|l|r|s|u]`) and should print something like `kiss oniguruma is not a valid command`.

**Comment by dylanaraps** [comment]
Will do. :+1:

**Comment by dylanaraps** [comment]
I very much appreciate these bug reports/enhancements. I'm too close to the project to catch things like this!

**Comment by naltun** [comment]
I'm glad to hear it, man. 👍 I'm really enjoying the work you two are doing here, and I'm having lots of fun exploring KISS.

I'll keep my eyes open. Stay tuned!

**Comment by dylanaraps** [comment]
Fixed.

**Comment by dylanaraps** [comment]
Also added a message for invalid commands. https://github.com/kisslinux/kiss/commit/0865856a9c5526d33a5eec55d4bb5ff26992e068

**Comment by naltun** [comment]
Woop!

**Comment by naltun** [comment]
🙌
