### ISSUE TITLE
[RFC] Alternatives system

### ISSUE THREAD

**Issue by konimex** [kisslinux/kiss#37]
## Rationale

In a system, we can have multiple implementations of a program, simple example: `vi`, which can mean either `vim` (`/usr/bin/vi` symlinked to `/usr/bin/vim`) or `busybox` (`/usr/bin/vi` symlinked to `/usr/bin/busybox`). Alternatives system will be needed, in particular, to resolve conflicts between multiple implementations (if any).

## Proposal

Packages can have an `alternatives` file. However these are to be installed to `/var/db/kiss/alternatives`. The directory structure would be something like this

```
/var/db/kiss/alternatives
├ vi        # (group)
│ ├ busybox # (package)
│ └ vim     # (package)
└ sh        # (group)
  ├ dash    # (package)
  ├ bash    # (package)
  └ busybox # (package)
```

Of course, the manifest in the respective packages will be updated to reflect this.

The `busybox` file in `vi` group directory would contain something like this:
```
busybox usr/bin/vi
busybox.1 usr/share/man/man1/vi.1
```
Where `$1` is `SOURCE` and `$2` is `TARGET`, much like a regular `ln` operation. Note the lack of leading `/`, since `$2` will be `${KISS_ROOT}/$2`. This can contain multiple symlinks, in case of multiple binaries, manpages and/or libraries.

When an "alternative" is selected, the contents will be the source and target for `ln` operations.

Also, we can add an operation `kiss alternatives`, something like this:
```
vi:
- busybox*
- vim
sh:
- bash
- busybox
- dash*
```

This is still a *very* rough concept, so if anyone has any questions/critiques, please state it.

**Comment by a-schaefers** [comment]
I was about to type of something similar, gentoo uses slots, and it works quite well. I too could use this feature with the work I'm doing in community.

**Comment by dylanaraps** [comment]
I've figured out a really simple way of implementing this. It requires no changes to the package format or the packages themselves. It will all happen dynamically. 

I'll work on implementing this shortly. :+1:

**Comment by AbsolutelyLudicrous** [comment]
Just curious, did you ever get around to implementing this? I've been thinking about Gentoo's virtual packages and the like, and how KISS needs something like that too.
