### ISSUE TITLE
Make 'kiss search' case insensitive

### ISSUE THREAD

**Issue by Aurubus** [kisslinux/kiss#58]

**Comment by dylanaraps** [comment]
Your other request to show all search matches has been added here: https://github.com/kisslinux/kiss/commit/718b774f3c8b2e46362aae598ed95050bdd165e2

Case insensitive search is not possible with POSIX `find` as `-iname` is a GNU extension. I realize that `busybox` implements it, however I want to stick to POSIX utilities where possible.

You **can** do a case insensitive search right now with `kiss search 'lib[Xx]*'`.

**Comment by Aurubus** [comment]
Nice! This is even better. 

Case insensitive search isn't really needed if you can use * anyways. I always found it annoying to go through every repository (or use globbing) to find out if you already packaged a dependency.
