### ISSUE TITLE
path/with/etc/is/removed/at/install

### ISSUE THREAD

**Issue by penguin-ff** [kisslinux/kiss#63]
Hi
I created a package. In the Manifest and in the archive file i see the path i want:
/usr/share/emacs/26.1/etc/charsets/

But kiss doesnt install it. In the source of kiss i found:
rsync --chown=root:root -WhHKa --no-compress "$1" --exclude etc 
So i think, thats a bug?

**Comment by penguin-ff** [comment]
BTW: Debian and Gentoo are also using this location. So i think, it should be installable there...

**Comment by dylanaraps** [comment]
If you look further down you'll see:

```sh
rsync --chown=root:root -WhHKa --no-compress --ignore-existing \
    "$tar_dir/$pkg_name/etc" "$KISS_ROOT/"
```

The package manager **does** install `/etc` only it happens afterwards and separately!

Can you upload the contents of the tarball's manifest file so I can try and investigate?

**Comment by penguin-ff** [comment]
Here we go :-)

[manifest.txt](https://github.com/kisslinux/kiss/files/3719205/manifest.txt)

Renamed it to manifest.txt so that github accept the file type...

**Comment by dylanaraps** [comment]
AH! I think you've found a bug, sorry for not seeing it soon. My hunch is that `--exclude etc` passed to `rsync` is being overly greedy. It should only exclude `/etc` but it seems to pick up any directory named `etc`. 

Working on a fix. :+1:

**Comment by penguin-ff** [comment]
You can try your fix with this package: https://github.com/penguin-ff/community/tree/emacs/community/emacs

It builds. But after the install it doesnt run, because of the missing "etc"

**Comment by dylanaraps** [comment]
Thanks for the test case :+1:

**Comment by dylanaraps** [comment]
This should be fixed in: https://github.com/kisslinux/kiss/commit/2208fd3f786fb8917fae703b99cf95ff3ce22f10

If you're willing you can add the single missing forward slash to your local copy and confirm. It's fine if you don't want to do this as I'm doing further tests regardless. :)

**Comment by penguin-ff** [comment]
One small slash for a man - one giant step for emacs ;-) Works like a charm now :-)

**Comment by dylanaraps** [comment]
Closing this. Will push the update later today. Want to do one more round of testing.
