### ISSUE TITLE
Restore minimal system

### ISSUE THREAD

**Issue by tristelune1** [kisslinux/kiss#66]
Hi, 

to write some packages I downloaded the installation file `kiss-chroot.tar.xz` and decompress it on `/mnt/kiss`. My goal is to test the build of packages and to not forget dependencies. So I chroot to `/mnt/kiss` and there I can try to build the package. For `zathura` I discovered for example that the dependency `gtk+3` was missing. It was already installed on my system, so I forgot the dependency.

The "problem" is: after building a package, I have to remove everything to test another one. I thought I could write what was installed, but I discovered it doesn't work, there is too much work. I still have to think about it, but do you have an idea what could be done ? A new feature for `kiss` or for `kiss-utils` ? 

I tested the distribution `Nutyx` and such a mechanism exists. The package manager for `Nutyx` is `cards`. With:

`cards create -r mypackage`

the system is restored to the same after a fresh installation and the package `mypackage` is installed. So we can't miss a dependency. The idea is to build in a chroot.

**Comment by dylanaraps** [comment]
In essence, the ability to revert to the packages only in the `chroot`?

**Comment by tristelune1** [comment]
Yes.

**Comment by dylanaraps** [comment]
This script can be used:

```sh
#!/bin/sh -ef
#
# Disable word-splittng warnings as they're safe here.
# shellcheck disable=SC2046
#
# kiss-reset: Remove all packages except for the base.

set -- \
    $(kiss l | while read -r pkg _; do
        case $pkg in
            baselayout|binutils|bison|busybox|bzip2|curl|flex|gcc|git|\
            gzip|kiss|libelf|libressl|linux-headers|m4|make|mandoc|musl|\
            perl|pkgconf|rsync|xz|zlib) ;;

            *) printf '%s\n' "$pkg" ;;
        esac
    done)

[ "$1" ] && {
    printf 'WARNING: This will remove \033[1m%s\033[m package(s).\n' "$#"
    printf 'Continue? [Enter/Ctrl+C]\n'
    read -r _ && kiss r "$@"
}
```

Please let me know if this satisfies your needs and I'll add it to `kiss-utils`.

**Comment by tristelune1** [comment]
Here is what I got:

````
./kiss-reset.sh
WARNING: This will remove 57 package(s).
Continue? [Enter/Ctrl+C]

-> Removing packages
-> zathura-pdf-poppler Removed successfully
-> zathura Removed successfully
-> poppler-glib Removed successfully
-> libjpeg-turbo Removed successfully
-> yasm Removed successfully
-> girara Removed successfully
-> json-c Removed successfully
-> gtk+3 Removed successfully
-> pango Removed successfully
-> libXft Removed successfully
-> libepoxy Removed successfully
-> libXinerama Removed successfully
-> libXi Removed successfully
-> libXcursor Removed successfully
-> libXcomposite Removed successfully
-> gdk-pixbuf Removed successfully
-> shared-mime-info Removed successfully
!> libxml2 Package is required by 'llvm', 'mesa'
````

I don't know in which order packages are removed, but it will be probably complicated with dependencies. I could imagine the following:

- if a package can't be removed because of depencies, the removal can be skipped. After that the user has to run the script once again. 
- the goal is to restore a minimal system and we know it should work. So why not using:

````
     read -r _ && KISS_FORCE=1 kiss r "$@"
````

I tried with `KISS_FORCE`, for the moment I'm able to chroot in my system. I will do more testing by writing other packages.

**Comment by dylanaraps** [comment]
`KISS_FORCE=1` should work fine. Will also do some testing. :+1:

**Comment by tristelune1** [comment]
Ok, it's time to package more software to see if it works. Thanks!

**Comment by dylanaraps** [comment]
Closing as `KISS_FORCE=1` works fine. :)

I'll move this to a `kiss-util` or the Wiki sometime today.
