### ISSUE TITLE
efivars not mounted in chroot

### ISSUE THREAD

**Issue by vx772** [kisslinux/kiss#69]
Hello,

Trying to use efibootmgr to boot a stub kernel, I found that the efivarfs was not mounted in /sys/firmware/efivars. I was able to simply execute `mount -t efivarfs none /sys/firmware/efi/efivars/` and everything worked as expected.

**Comment by dylanaraps** [comment]
Hello,

I'll add this information to the Wiki and installation guide. I don't want to mount the `efivars` `rw` automatically as this is very unsafe (*`rm -rf` can brick your motherboard.*). I think it's a lot better for the user to do it manually and **know** when they're mounted, how they're mounted etc.

**Comment by vx772** [comment]
Thanks. I agree with your reasoning about not automatically mounting it.

**Comment by dylanaraps** [comment]
Wiki page added: https://getkiss.org/wiki/mounting-uefi-variables

Also added a note to the installation guide.

Thanks :+1:
