### ISSUE TITLE
Installed package is now requiring depps I didnt' specify

### ISSUE THREAD

**Issue by a-schaefers** [kisslinux/kiss#75]
Okay, I was testing "util-linux", packaged it, compiled it, installed it all without error, using the following commit https://github.com/a-schaefers/community/commit/9648b16585559851ffea0a706a84b8e9975c5660

The only depp I specified was "make", and it won't let me kiss r util-linux, it returns:

util-linux Package is required by 'e2fsprogs', 'eudev', 'gdk-pixbuf', 'glib', 'gtk+2', 'libSM', 'libXmu', 'libXt', 'python'

AND to top it all off, I can't find the package installed where I specified in the build file, /opt/util-linux doesn't exist.

What just happened?

**Comment by dylanaraps** [comment]
These packages dynamically linked to `util-linux` as it was on the system and the package manager picked up on this to prevent linker errors were `util-linux` to be removed.

You can remedy this by using `KISS_FORCE=1 kiss r util-linux` and rebuilding the above list of packages. You could also modify the configure flags of the above packages **if** they provide the ability to disable linking to `util-linux`.

**Comment by a-schaefers** [comment]
Ok. And why did  /opt/util-linux/ not exist like I thought it should, based on:

./configure --prefix=/opt/util-linux

make DESTDIR="$1" install

**Comment by a-schaefers** [comment]
on closer look are you sure i didn't run into a bug?

i just noticed my checksum file is totally wrong, not sure how it even built the package to begin

**Comment by dylanaraps** [comment]
`util-linux` is available in `core` and the official repository package was most likely used for the build **and** already installed.

**Comment by a-schaefers** [comment]
Okay that makes a lot of sense now. Too funny.  Closing this.
