### ISSUE TITLE
Display overall build progress

### ISSUE THREAD

**Issue by aaronNGi** [kisslinux/kiss#76]
When building more than a few packages, there is no real way of keeping track of the progress. Sometimes it's possible to figure out the current package from the compiler output, but there is no convenient way of knowing if the current package is the 5th or very last one in the queue (besides remembering the order).

It would be nice if `kiss` displayed the current package number together with the total amount of packages to build. Given that the total amount of packages is available as `$#` in `pkg_build()` and only a counter, keeping track of the current package number, would have to be added, it seems trivial to implement.

I would definitely change the output in `build_pkg()` to someting like **[foo] Starting build 4 of 10**. Additionally, the terminal title could be set using the OSC escape sequence `\e]0;foobar\a`. The latter would be nice but is not supported by all terminals, so I'm not sure what to do with it. Without terminal titles, one could simply redirect the output of `kiss` to a file and then lookup the build status there. As an alternative to setting the terminal title, something like gentoos `--quiet-build` option could be explored.

I'm willing to implement that feature myself but wanted to first get some input on the whole idea and the different options.

**Comment by dylanaraps** [comment]
Done. :)
