### ISSUE TITLE
User prompts

### ISSUE THREAD

**Issue by aaronNGi** [kisslinux/kiss#77]
Because it's easy to accidentally input enter multiple times (keyboard repeat, parkinson's), most tools who prompt the user have cancel be the default option. I think it would be better to use the more "standard" `... (y/N)?` instead.

The current function is definitely cute with it's 2 lines but doing yes/No is quite trivial too. Maybe something like:

```sh
prompt() {
    [ -t 0 ] || return

    while :; do
        log "$* (y/N)? "
        read -r reply
        case $reply in
            [yY]|[yY][eE][sS]) return 0 ;;
            [nN]|[nN][oO]|'') return 1 ;;  # we could also exit() here I guess
        esac
    done
}

...

[ $# -gt 1 ] && {
    prompt "Install built packages [$*]" && {
        args i "$@"
        return
    }
    exit $?
}
```

**Comment by dylanaraps** [comment]
This requires the user to type `[y]es`/`[n]o` and then `Enter` no? A more typical prompt can be implemented in POSIX shell using `dd`/`stty`. See how I have done it in `pash` here: https://github.com/dylanaraps/pash/blob/master/pash#L103-L124

**Comment by aaronNGi** [comment]
Yeah, it would basically require one more keystroke for "continue". Having to type less is definitely preferable but I like my suggestion because it's how coreutils do it if you use the `-i` option of `rm`, `cp` etc. Same for the non-menu based kernel configuration.

I think at this point I'm more after using a more typical way of prompting the user than preventing accidental enter presses. Honestly, the KISS way would be to just keep it as is :)
