### ISSUE TITLE
chroot builds

### ISSUE THREAD

**Issue by a-schaefers** [kisslinux/kiss#78]
Correct me if I am wrong, but it would be nice if we built using chroots so that we could figure out explicitly what depends we need to build stuff, thusly making more trusty build files for everybody.

**Comment by dylanaraps** [comment]
This can already be done right now (though manually). The installation tarball is also a fully working `chroot` environment. 

A simple script could be written to automatically create/destroy KISS chroot environments while doing a build in this environment in-between. 

I'll think about how best to implement this though it shouldn't be too difficult.

**Comment by dylanaraps** [comment]
This simple script will setup and create a simple KISS `chroot` and drop you inside of it. Once you type `exit` the `chroot` is then destroyed. The script will download/extract the original `chroot` `tarball` once (cache) and will then simply `cp` the original to a temporary and unique directory.

You can make any modifications you like to the `kiss-chroot/` directory as this will remain untouched by the script unless it is removed. Think of this as how you could add a repository etc. You'd just need to `kiss-chroot` into the "master" and make any changes you'd like to include in each temporary `chroot`.

To reset the `chroot` master simply remove `kiss-chroot/`. To reset and redownload the `chroot` simply remove `kiss-chroot/` and `kiss-chroot.tar.xz`.

To make more sense of it, here's what the directory hierarchy looks like:

```
kiss-chroot.tar.xz  # The cached chroot tarball. 
kiss-chroot/        # The "master"/"base" chroot (make your changes here).
chroot-$pid/        # A copy of kiss-chroot/ which is created/destroyed using the script.
```

```sh
#!/bin/sh -e
#
# Create/destroy temporary chroots.

log() {
    printf '\033[31;1m->\033[m %s.\n' "$@"
}

clean() {
    log "Destroying chroot"
    su -c "rm -rf chroot-$pid" || clean
}

pid=$$

cd "${cac_dir:=$KISS_ROOT${XDG_CACHE_HOME:-$HOME/.cache}/kiss}"

[ -f kiss-chroot.tar.xz ] || {
    log "Downloading chroot tarball"
    wget https://dl.getkiss.org/kiss-chroot.tar.xz
}

[ -d kiss-chroot ] || {
    log "Extracting chroot"
    tar xvf kiss-chroot.tar.xz
}

log "Creating temporary chroot"
cp -a kiss-chroot "chroot-$pid"

trap clean EXIT INT

log "Entering chroot"
su -c "kiss-chroot chroot-$pid"
```

**Comment by dylanaraps** [comment]
Any thoughts on the above script?

**Comment by a-schaefers** [comment]
It looks slick, sorry I'm late to this, I haven't even been able to test it yet.
