### ISSUE TITLE
pkg_fixdeps sometimes adds an empty line on depends file

### ISSUE THREAD

**Issue by konimex** [kisslinux/kiss#89]
## Issue

Sometimes the package manager adds an empty line on `depends`, even when `depends` doesn't exist at all.

```
-> gmake Checking for missing dependencies
--- depends
+++ depends-new
@@ -0,0 +1 @@
+
```

```
-> pigz Checking for missing dependencies
--- depends
+++ depends-new
@@ -1 +1,2 @@
+
 zlib
```

## How to reproduce

Build a random package, in my case, it's GNU `make` and `pigz`.

Logs: 
- https://termbin.com/puta (GNU make, `set -x` -- what an unfortunate link)
- https://termbin.com/yugl (pigz, `set -x`)
- https://termbin.com/p8gs (pigz, `set +x`)

**Comment by dylanaraps** [comment]
Fixed
