### ISSUE TITLE
Small misspelling in comments

### ISSUE THREAD

**Issue by periish** [kisslinux/kiss#90]
https://github.com/kisslinux/kiss/blob/935be97f7d37c0b8c375cf33ee4dd99652b77b69/kiss#L391
# This **funcion** runs as a sub-shell to avoid having to 'cd' back to the

**Comment by periish** [comment]
should be function :p

**Comment by dylanaraps** [comment]
Fixed in: https://github.com/kisslinux/kiss/commit/22b4af93424e2b2e796ed87675296d30398d2b3d

Thanks :+1:
