### ISSUE TITLE
sbase find issue

### ISSUE THREAD

**Issue by cemkeylan** [kisslinux/kiss#95]
So sbase `find` is quite problematic. I have checked the manpage and I don't see an entry about -mindepth and -maxdepth. Those might not be POSIX.

```
-> Resolving dependencies
find: paths must precede expression: -mindepth
!> Package 'sbase' not in any repository
```

**Comment by dylanaraps** [comment]
`sed` usage also fixed.

**Comment by dylanaraps** [comment]
sbase fully works now.
