### ISSUE TITLE
Question re: alternatives

### ISSUE THREAD

**Issue by a-schaefers** [kisslinux/kiss#97]
```
KISS_CHOICE=1 kiss i sbase ubase
kiss i busybox 
```
results in busybox overwriting sbase/ubase without warning of conflict / requiring KISS_CHOICE=1 for the busybox install command.

This means that next time busybox is updated, then sbase or ubase will be purged from a user's system.

Is there further steps required for a migration towards sbase/ubase and away from busybox, or is this a bug?

Thanks

**Comment by a-schaefers** [comment]
I have just learned there is a `kiss a' feature I forgot about, e.g.

kiss a | grep ^sbase | kiss a -

Maybe that is all I needed to do?

**Comment by dylanaraps** [comment]
You need to explicitly use `kiss a` to swap to `ubase`/`sbase`. `kiss i busybox` will of course work as `kiss i sbase ubase` with `KISS_CHOICE=1` doesn't immediately swap the system's utilities.

**Comment by dylanaraps** [comment]
Yes

**Comment by dylanaraps** [comment]
NOTE: You need to swap back to busybox tar after running that command: `kiss a busybox /usr/bin/tar`.

**Comment by a-schaefers** [comment]
let's leave this here until documentation is complete

**Comment by a-schaefers** [comment]
> NOTE: You need to swap back to busybox tar after running that command: `kiss a busybox /usr/bin/tar`.

```
kiss a busybox /usr/bin/tar
-> Swapping '/usr/bin/tar' from 'sbase' to 'busybox'
Password:
usage: su [-lp] [username]

```

Hehe apparently not only tar but su too has issues

**Comment by dylanaraps** [comment]
Documentation has been added to the README. Man page will follow in a few mins.

https://github.com/kisslinux/kiss#alternatives-system
